### PR TITLE
fix(ToggleButtonGroup): Fix broken css styles.

### LINKED ISSUE #2141: ButtonGroup: Broken css styles.
Some styles are missing for `ButtonGroup` and `ToggleButtonGroup`.
At first sight, this issue appeared after [this](https://github.com/cengage/react-magma/pull/2060) PR.
We need to check all styles for all cases to ensure we have a stable version.
[4.10.1.-next-22](https://codesandbox.io/p/sandbox/react-magma-example-forked-v4w7fj)

**Expected behavior**
All styles should be fixed for `ButtonGroup` and `ToggleButtonGroup` components.
[4.10.1](https://codesandbox.io/p/sandbox/react-magma-example-forked-9kxgcl)

**Screenshots**

Image

**Additional context**
Slack [original message](https://cengage.slack.com/archives/C8Y4FR63U/p1766160543448199)

### PR DESCRIPTION
**Pull request by olehnoskov-cengage**
Closes: #2141 

## What I did
- Fixed broken CSS styles for `ToggleButtonGroup` component.                                                          

## Screenshots
Screenshot from 2025-12-24 11-47-18

## Checklist 
- [x] changeset has been added
- [x] Pull request is assigned, labels have been added and ticket is linked
- [x] Pull request description is descriptive and testing steps are listed
- [ ] Corresponding changes to the documentation have been made
- [ ] New and existing unit tests pass locally with the proposed changes
- [ ] Tests that prove the fix is effective or that the feature works have been added

## How to test
Go to Storybook -> ToggleButtonGroup -> Alignment Example -> example should have correct css ctyles.
Go to Storybook -> ButtonGroup -> Default -> example should have correct css ctyles.

### CODE REVIEW

**Review by moathabuhamad-cengage — APPROVED** [review]

File: packages/react-magma-dom/src/components/ButtonGroup/index.tsx [hunk 1]
```diff
@@ -358,6 +358,40 @@ const StyledButtonGroup = styled.div<{
         }
       `};
   }
+
+  // Styles for ToggleButtonGroup
+  > li > button {
```
Comment (silvalaura) [inline packages/react-magma-dom/src/components/ButtonGroup/index.tsx:329]: Are these styles duplicated above? Should we make them a variable so they don't get out of sync, or can we do `> li, > li > button` or does that break something?

Comment (olehnoskov-cengage) [reply packages/react-magma-dom/src/components/ButtonGroup/index.tsx:329]: Yes, some styles are duplicated. Refactored.

**Review by nikitaorliak-cengage — APPROVED** [review]
