### PR TITLE
fix(Modal): Modal disabled background click focus fix.

### LINKED ISSUE #1417: Modal: When using `isBackgroundClickDisabled`, nothing in the modal is focusable
**Describe the bug**
If `isBackgroundClickDisabled` is true, nothing in the modal is focusable by mouse or clickable. Text is also not selectable.

**To Reproduce**
1. Go to https://codesandbox.io/p/sandbox/s2hcml
2. Click on Show Modal
3. Try to click on any of the interactive elements, or select the text

**Expected behavior**
- The prop `isBackgroundClickDisabled` should not affect the ability to click on elements within a modal

**Notes**
- Notice how in the example, the bug only happens on the first modal, not the nested one
- The latest change in modal related to this was to support the background color with nested modals, so that should still function when this is fixed

### PR DESCRIPTION
**Pull request by chris-cedrone-cengage**
Issue: # [1417](https://github.com/cengage/react-magma/issues/1417)

## What I did
- Restructured DOM order to help with focus issue while using `isBackgroundClickDisabled` prop.

## Screenshots:
nested
clickable

## Checklist 
- [X] changeset has been added
- [X] Pull request description is descriptive
- [N/A] I have made corresponding changes to the documentation
- [X] New and existing unit tests pass locally with my changes
- [N/A] I have added tests that prove my fix is effective or that my feature works

## How to test
- Storybook
- Open Background Click Disabled story
- Verify you can now select text on the modal and click the buttons
- Open Modal In A Modal story
- Go into second modal and verify overlay is beneath it properly

### CODE REVIEW

**Comment by silvalaura** [comment]
The background does not work as expected when the modal has a lot of content and needs to scroll: https://storybook-preview-1418--upbeat-sinoussi-f675aa.netlify.app/?path=/story/modal--long-content-with-scrolling

**Comment by silvalaura** [comment]
Same problem 😿 
image

File: packages/react-magma-dom/src/components/Modal/Modal.tsx [hunk 1]
```diff
@@ -373,6 +373,70 @@ export const Modal = React.forwardRef<HTMLDivElement, ModalProps>(
...
+              aria-label={!header ? ariaLabel : null}
+              aria-modal={true}
+              data-testid={testId}
+              id={id}
+              onClick={isBackgroundClickDisabled ? null : handleModalClick}
+              onMouseDown={
+                isBackgroundClickDisabled ? null : handleModalOnMouseDown
+              }
+              role="dialog"
+              style={containerStyle || (modalCount >= 2 && { zIndex: '999' })}
```
Comment (silvalaura) [inline packages/react-magma-dom/src/components/Modal/Modal.tsx:387]: This wouldn't work if the user is using the `containerStyle` prop

**Review by silvalaura — APPROVED** [review]
