### PR TITLE
Fix:  [Accessibility] [Global] [Datagrid] Selectable and Sortable> 'Sort Rows' button is unnecessarily marked-up as column header

### LINKED ISSUE #1946: [Accessibility] [Global] [Datagrid] Selectable and Sortable> 'Sort Rows' button is unnecessarily marked-up as column header
**Environment:**
Windows 11/Chrome 137/JAWS 2025
Windows 11/Edge 136/NVDA 2025
Mac 15/Safari/VoiceOver

**Steps to Reproduce:**
1. Open the URL – https://react-magma.cengage.com/version/4.9.1/api/tooltip/
2. Turn on the screen reader (JAWS/NVDA/VoiceOver).
3. Navigate to the Datagrid component page from the left navigation.
4. Go to the Selectable and Sortable section.
5. Navigate to the data table and use table navigation keys (Ctrl + Alt + Arrow keys) to move from the second column (Name) to the first column (checkbox) in any row.
5. Observe the screen reader announcement for the cell in the first column.

**Actual Result:**
While navigating from the second column to the first column within any data row, the screen reader unnecessarily announces the “Sort Rows” button as the column header for the Select Row checkbox cells. This happens because the Sort Rows control is incorrectly marked up using a <th> element or with role="columnheader", which semantically defines it as a header for that column.

Since the Sort Rows button is placed in the first column and is not meant to describe the contents of that column (i.e., checkboxes), the incorrect use of a column header role leads to semantic confusion. Screen readers interpret this button as the header for the checkbox cells, which is misleading and not meaningful for users.

Refer to screencast:
https://app.screencast.com/znprf2bRRf7Zu

Note: This issue is reproducible for all data rows in the Selectable and Sortable variant of the Datagrid component.

**Expected Result:**
The Sort Rows button should not be marked up as a column header if it does not semantically describe or relate to the contents of the first column.

**User Impact:**
Incorrect use of column headers leads to semantic inaccuracy and confusion for screen reader users. They may misunderstand the purpose of the checkbox column or incorrectly assume that the “Sort Rows” button applies to checkbox selection, which it does not. This breaks the table’s logical structure and disrupts navigation and comprehension.

WCAG Guideline: 1.3.1 Info and Relationships (A)

**Bug Fix Recommendation:**
a) Remove the th element or role="columnheader" from the Sort Rows button if it is not intended to be a column header.
b) Mark the button as a standard <button> element within a <td> or equivalent cell context.
c) Ensure all data table headers accurately reflect the column content they represent, especially for users navigating with assistive technologies.

### PR DESCRIPTION
**Pull request by moathabuhamad-cengage**
Closes: #1946

## What I did

Fixed semantic markup for Sort Rows button in selectable and sortable variant. The button now uses a `<td>` element instead of `<th>`, preventing screen readers from incorrectly announcing it as a column header for checkbox cells.
## Checklist 
- [x] changeset has been added
- [x] Pull request is assigned, labels have been added and ticket is linked
- [x] Pull request description is descriptive and testing steps are listed
- [x] Corresponding changes to the documentation have been made
- [x] New and existing unit tests pass locally with the proposed changes
- [x] Tests that prove the fix is effective or that the feature works have been added

## How to test

got to storybook Datagrid--selectable-and-sortable test screen reader output

### CODE REVIEW

**Comment by olehnoskov-cengage** [comment]
Tested on Windows 11/Chrome
NVDA announces the `Sort Rows ` button instead of the first table header.
[Screencast from 26.11.25 11:27:08.webm](https://github.com/user-attachments/assets/cb3fb51e-fead-4d76-96ff-aafbaaf170b2)

File: packages/react-magma-dom/src/components/Table/TableRow.tsx [hunk 1]
```diff
@@ -183,6 +182,32 @@ const StyledTableRow = styled.tr<{
     `};
 `;
 
+const HeaderStyledCell = styled(TableCell)<{
+  density?: TableDensity;
+  hasSquareCorners?: boolean;
+  isInverse?: boolean;
+}>`
+  &&& {
```
Comment (nikitaorliak-cengage) [inline packages/react-magma-dom/src/components/Table/TableRow.tsx:190]: Do we need `&&&` here? It is necessary for `:first-child` because of its specificity, but here, in my opinion, we can remove this block and leave only:
```
}>`
background: ...;
...

&&&:first-child {
...
}
`;
```

Comment (moathabuhamad-cengage) [reply packages/react-magma-dom/src/components/Table/TableRow.tsx:190]: yes its needed, styles break without it 
image

**Review by nikitaorliak-cengage — APPROVED** [review]

**Comment by moathabuhamad-cengage** [comment]
> Tested on Windows 11/Chrome NVDA announces the `Sort Rows ` button instead of the first table header. [Screencast from 26.11.25 11:27:08.webm](https://github.com/user-attachments/assets/cb3fb51e-fead-4d76-96ff-aafbaaf170b2)

it works make sure to use up and down arrows not Tab to read it, also its the same behavior we currently have on dev

**Review by olehnoskov-cengage — APPROVED** [review]

**Comment by moathabuhamad-cengage** [comment]
> Tested on Windows 11/Chrome NVDA announces the `Sort Rows ` button instead of the first table header. [Screencast from 26.11.25 11:27:08.webm](https://github.com/user-attachments/assets/cb3fb51e-fead-4d76-96ff-aafbaaf170b2)

it works if you use arrow keys but not tab not sure whats the acceptable behaviour

**Comment by silvalaura** [comment]
Remaining item in this PR is checking the selectable and sortable example and determining why it reads that `table is sorted by name`, correct?

**Comment by moathabuhamad-cengage** [comment]
> Remaining item in this PR is checking the selectable and sortable example and determining why it reads that `table is sorted by name`, correct?

confirmed it's it sthe example, will fix before merging 

image
