### PR TITLE
fix(Dropzone): accessibility issues

### LINKED ISSUE #2084: [Accessibility] [Global] [Dropzone] Improve focus and announcements
[A11Y-541](https://jira.cengage.com/browse/A11Y-541)
[A11Y-542](https://jira.cengage.com/browse/A11Y-542)
[A11Y-547](https://jira.cengage.com/browse/A11Y-547)

**Issue 1:**
**[Accessibility] [Global] [Dropzone] Basic Usage> Browse Files> No confirmation message is announced when any file is added or removed**

Environment:
Windows 11/Chrome 137/JAWS 2025
Windows 11/Edge 136/NVDA 2025
Mac 15/Safari/VoiceOver

Steps to Reproduce:

1. Open the URL – https://react-magma.cengage.com/version/4.9.1/api/tooltip/
2. Turn on the screen reader (JAWS/NVDA/VoiceOver).
3. Navigate to the Dropzone component page from the left navigation.
4. Under the Basic Usage section, navigate to the Browse Files button and activate it.
5. Select and upload a file from the local machine.
6. Observe whether a confirmation message is announced by the screen reader.
7. Now remove the uploaded file and observe again.

Actual Result:

When a file is added via the Browse Files button or removed from the dropzone list, the action is visually reflected on screen (e.g., file name appears or disappears), but no audible confirmation is announced by the screen reader. This leaves screen reader users unaware of the success or failure of their actions related to file uploads or deletions.

Refer to screencast:
https://app.screencast.com/tJts3D9TR75zJ

Note: This issue is applicable globally across all dropzone implementations that involve file additions and deletions.

Expected Result:

Whenever a file is added or removed from the dropzone, a confirmation message should be announced automatically, such as:
“File XYZ.pdf has been added.”
“File XYZ.pdf has been removed.”

This feedback should be conveyed using a live region to ensure screen reader users are kept informed about the file status in real time.

User Impact:
Without status announcements, users who rely on screen readers cannot determine whether their file has been successfully uploaded or deleted. This may result in duplicate actions, uncertainty, and a frustrating user experience.

WCAG Guideline: 4.1.3 Status Messages (AA)

Bug Fix Recommendation:

a) Implement an aria-live="polite" region for dynamically announcing file status updates.
b) Ensure programmatic announcements are triggered on both file upload and file removal events.
c) Ensure consistent and accurate messaging across all screen reader environments.

**Not a component problem, but the doc example can be updated to use the Announce component**

**Issue 2:**
**[Accessibility] [Global] [Dropzone] Basic Usage> Screen reader focus is lost upon removing any file**

Environment:
Windows 11/Chrome 137/JAWS 2025
Windows 11/Edge 136/NVDA 2025
Mac 15/Safari/VoiceOver

Steps to Reproduce:

1. Open the URL – https://react-magma.cengage.com/version/4.9.1/api/tooltip/
2. Turn on the screen reader (JAWS/NVDA/VoiceOver).
3. Navigate to the Dropzone component page from the left navigation.
4. Under the Basic Usage section, use the Browse Files button to upload one or more files.
5. Navigate to and activate the Remove (or Delete) button associated with any uploaded file.
6. Observe the screen reader focus behavior after file removal.

Actual Result:

After activating the Remove button for an uploaded file:

JAWS intermittently moves focus to the top of the page, especially when navigating using arrow keys.
NVDA moves focus to the unrelated “EDIT IN CODESANDBOX” button.
In both cases, screen reader users lose contextual focus. The focus does not return to the Browse Files button or the Remove button of the next available file, causing disorientation.

Refer to screencast:
https://app.screencast.com/Pcw0RPmqsCoeK

Note: This issue is reproducible across all Dropzone variants involving file removal or deletions, including:

a) Handle File Processing
b) Deleting Files

Expected Result:

Upon removing a file:

Focus should shift either to the Remove button of the next available file (if present), or return to the Browse Files button.
This maintains logical focus flow and allows screen reader users to continue interacting with the component without interruption.

User Impact:
Unexpected focus loss creates significant usability challenges for screen reader users, especially in file upload workflows. Users may lose track of their location on the page, forcing them to restart navigation or abandon the task altogether.

WCAG Guideline: 2.4.3 Focus Order (A)

**Issue 3:**
**[Accessibility] [Dropzone] Handle File Processing> Browse Files> Upload Files> JAWS focus is lost upon activating 'Upload Files' button**

Environment:
Windows 11/Chrome 137/JAWS 2025

Steps to Reproduce:

1. Open the URL – https://react-magma.cengage.com/version/4.9.1/api/tooltip/
2. Turn on the screen reader (JAWS).
3. Navigate to the Dropzone component page from the left navigation.
4. Scroll to the Handle File Processing section.
5. Use the Browse Files button to upload one or more files.
6. Navigate to and activate the Upload Files button using TAB or arrow keys.
7. Observe the screen reader focus behavior using arrow keys after activation.

Actual Result:

Upon activating the Upload Files button, JAWS focus intermittently jumps to the top of the page, especially when navigating via arrow keys. It does not remain within the Dropzone component or move to the uploaded file status region. As a result, users lose their place on the page and must manually navigate back to verify upload progress or status.

Refer to screencast:
https://app.screencast.com/9RykXNVzTaR9X

Expected Result:

Screen reader focus should remain within the Dropzone area and ideally move to the status region or the first uploaded file item. Users should be able to continue interacting with the component without disorientation.

User Impact:
Loss of focus causes disorientation and forces screen reader users to manually navigate back to the Dropzone component, reducing efficiency and creating confusion about whether their action (upload) was successful.

WCAG Guideline: 2.4.3 Focus Order (A)

Bug Fix Recommendation:

a) After activating the Upload Files button, move programmatic focus to the first uploaded file or a designated upload confirmation/status region.
b) Ensure the status region is within logical reading order and provides clear feedback.
c) Test across multiple screen readers to ensure consistent focus behavior.

### PR DESCRIPTION
**Pull request by nikitaorliak-cengage**
Closes: #2084, #2085, #2086

## What I did

Fix a few issues for Dropzone

## Checklist 
- [x] changeset has been added
- [x] Pull request is assigned, labels have been added and ticket is linked
- [x] Pull request description is descriptive and testing steps are listed
- [ ] Corresponding changes to the documentation have been made
- [x] New and existing unit tests pass locally with the proposed changes
- [ ] Tests that prove the fix is effective or that the feature works have been added

## How to test

1. Open Docs/Storybook -> Dropzone -> Turn on NVDA/VO -> Upload, Remove, Delete file('s) -> Check screenreader's behavior
2. Open Docs/Storybook -> Dropzone -> Upload a few elements -> Check that focus moves to the `Browse Files` button after uploading -> Remove/Delete item -> Check that focus moves to the `Browse Button` too 
3. Open Docs/Storybook -> Dropzone -> Open DevTools -> Upload files -> Check new HTML structure (Items should be wrapped in ul > li)
4. Open Docs/Storybook -> Dropzone -> Upload File -> Turn on NVDA/VO -> Focus on `Delete/Remove` button -> Check that screenreaders announce `Delete/Remove file (file name)`
5. Open Docs/Storybook -> Dropzone -> Turn on NVDA/VO -> Focus on the `Browse file` button -> Screenreaders should announce helper messages
6. Open Docs/Storybook -> Dropzone -> Turn on NVDA/VO -> Upload any file -> During loading, screenreaders should announce status -> After successful loading, it should announce `(file name) uploaded successfully`
7. Open Docs -> Dropzone -> Handle File Processing section -> Upload a file -> Click on `Upload files` button -> After uploading, focus should move back to the `Upload files` button

### CODE REVIEW

File: packages/react-magma-dom/src/i18n/default.ts [hunk 1]
```diff
@@ -197,6 +193,9 @@ export const defaultI18n: I18nInterface = {
     bytes: 'Bytes',
     deleteFile: 'Delete file',
     removeFile: 'Remove file',
+    fileAdded: 'File {fileName} has been added',
+    fileRemoved: 'File {fileName} has been removed',
+    fileDeleted: 'File {fileName} has been deleted',
```
Comment (silvalaura) [inline packages/react-magma-dom/src/i18n/default.ts:199]: Removed & deleted are the same thing

Comment (nikitaorliak-cengage) [reply packages/react-magma-dom/src/i18n/default.ts:199]: In the code, we have two different functions — `handleDeleteFile` and `handleRemoveFile` — as well as two different buttons for them, so I added two different labels for them

**Review by olehnoskov-cengage — COMMENTED** [review]
@nikitaorliak-cengage 
`Issue 3:
[Accessibility] [Dropzone] Handle File Processing> Browse Files> Upload Files> JAWS focus is lost upon activating 'Upload Files' button` wasn't fixed.

**Comment by nikitaorliak-cengage** [comment]
> @nikitaorliak-cengage `Issue 3: [Accessibility] [Dropzone] Handle File Processing> Browse Files> Upload Files> JAWS focus is lost upon activating 'Upload Files' button` wasn't fixed.

Does it work for other OS/Browsers? Focus should be moved to the `Browse File` button after uploading any file (Check [THIS](https://github.com/cengage/react-magma/pull/2332/changes/71e32d41ea20ffe96540a52401c86e549ecce9ba) commit)

File: website/react-magma-docs/src/pages/api/dropzone.mdx [hunk 2]
```diff
@@ -10,7 +10,11 @@ title: Dropzone
   commonly used within forms but may also exist on their own.
 </LeadParagraph>
 
-<Alert variant="warning"><strong>Important!</strong> Dropzone is imported from <code>@react-magma/dropzone</code> which must be installed as a peer dependency.</Alert>
+<Alert variant="warning">
```
Comment (olehnoskov-cengage) [inline website/react-magma-docs/src/pages/api/dropzone.mdx]: Please, roll back these changes cuz it brokes the Alert example.

**Review by olehnoskov-cengage — APPROVED** [review]

File: packages/dropzone/src/components/dropzone/Dropzone.tsx [hunk 3]
```diff
@@ -243,9 +255,26 @@ export const Dropzone = React.forwardRef<HTMLInputElement, DropzoneProps>(
...
+
+        if (acceptedFiles.length > 0) {
+          const fileNames = acceptedFiles.map(file => file.name).join(', ');
+          const message =
+            acceptedFiles.length === 1
+              ? (
+                  i18n.dropzone as unknown as { fileAdded?: string }
+                ).fileAdded?.replace(/\{fileName\}/g, fileNames) ||
+                `File ${fileNames} has been added`
+              : `${acceptedFiles.length} files have been added: ${fileNames}`;
```
Comment (silvalaura) [inline packages/dropzone/src/components/dropzone/Dropzone.tsx]: we should i18n these strings

File: packages/dropzone/src/components/dropzone/Dropzone.tsx [hunk 4]
```diff
@@ -275,50 +304,84 @@ export const Dropzone = React.forwardRef<HTMLInputElement, DropzoneProps>(
...
+
+      if (onRemoveFile && typeof onRemoveFile === 'function') {
         onRemoveFile(removedFile);
+      }
+
+      const message =
+        (
+          i18n.dropzone as unknown as { fileRemoved?: string }
+        ).fileRemoved?.replace(/\{fileName\}/g, removedFile.name) ||
+        `File ${removedFile.name} has been removed`;
```
Comment (silvalaura) [inline packages/dropzone/src/components/dropzone/Dropzone.tsx]: i18n

File: packages/dropzone/src/components/dropzone/Dropzone.tsx [hunk 5]
```diff
@@ -275,50 +304,84 @@ export const Dropzone = React.forwardRef<HTMLInputElement, DropzoneProps>(
...
+
+      if (onDeleteFile && typeof onDeleteFile === 'function') {
         onDeleteFile(removedFile);
+      }
+
+      const message =
+        (
+          i18n.dropzone as unknown as { fileDeleted?: string }
+        ).fileDeleted?.replace(/\{fileName\}/g, removedFile.name) ||
+        `File ${removedFile.name} has been deleted`;
```
Comment (silvalaura) [inline packages/dropzone/src/components/dropzone/Dropzone.tsx]: i18n

File: packages/dropzone/src/components/dropzone/Dropzone.tsx [hunk 6]
```diff
@@ -275,50 +304,84 @@ export const Dropzone = React.forwardRef<HTMLInputElement, DropzoneProps>(
...
                   status: 'pending',
                 },
               })
             : file
         )
       );
+
+      // Announce progress every 25% to avoid too many announcements
+      if (progressProps.percent > 0 && progressProps.percent % 25 === 0) {
+        const message = `Uploading ${progressProps.file.name}, ${progressProps.percent}% complete`;
```
Comment (silvalaura) [inline packages/dropzone/src/components/dropzone/Dropzone.tsx]: i18n

File: packages/dropzone/src/components/dropzone/Dropzone.tsx [hunk 7]
```diff
@@ -329,38 +392,29 @@ export const Dropzone = React.forwardRef<HTMLInputElement, DropzoneProps>(
             : file
         )
       );
+
+      // Announce successful upload
+      const message = `${finishedProps.file.name} uploaded successfully`;
```
Comment (silvalaura) [inline packages/dropzone/src/components/dropzone/Dropzone.tsx]: i18n :)

File: packages/dropzone/src/components/dropzone/Dropzone.tsx [hunk 8]
```diff
@@ -188,6 +190,13 @@ const Wrapper = styled.div<{ isInverse?: boolean }>`
   padding: ${({ theme }) => theme.spaceScale.spacing01};
 `;
 
+const PreviewList = styled.div`
```
Comment (silvalaura) [inline packages/dropzone/src/components/dropzone/Dropzone.tsx]: Why not `styled.ul` instead of styledAs="ul"?

File: website/react-magma-docs/src/pages/api/dropzone.mdx (hunk 2 above)
Comment (silvalaura) [reply website/react-magma-docs/src/pages/api/dropzone.mdx]: What about this change?

Comment (silvalaura) [reply website/react-magma-docs/src/pages/api/dropzone.mdx]: image

**Review by moathabuhamad-cengage — APPROVED** [review]

**Review by silvalaura — APPROVED** [review]
