### PR TITLE
fix(Combobox, Select, Datagrid): fix accessibility issues

### LINKED ISSUE #2369: Datagrid: Table pagination accessibility issues
1. The current/active page is not identified as “current page.” Users cannot determine which page is currently selected (screenshot 1)
2. Enter key does not activate the combo box. Space key activates it but displays an empty list.([https://media-cdn.atlassian.com/file/17f6223e-affd-46ea-b4a5-d3587b9298af/artifact/video[…]lZCI6ZmFsc2V9.pReng9mjTL6tAzy37vSc2tOq6s6mQKnjWaMudv_ur6Q](https://media-cdn.atlassian.com/file/17f6223e-affd-46ea-b4a5-d3587b9298af/artifact/video_1280.mp4/binary/cdn?client=f8316f75-1151-484f-860f-73a63cdf679e&collection=&max-age=2592000&token=eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJmODMxNmY3NS0xMTUxLTQ4NGYtODYwZi03M2E2M2NkZjY3OWUiLCJhY2Nlc3MiOnsidXJuOmZpbGVzdG9yZTpmaWxlOjE3ZjYyMjNlLWFmZmQtNDZlYS1iNGE1LWQzNTg3YjkyOThhZiI6WyJyZWFkIl19LCJleHAiOjE3NzQzNjEyODcsIm5iZiI6MTc3NDM2MDM4NywiYWFJZCI6IjcxMjAyMDplYWE3Y2UwMy1iYjMxLTQzOTYtYmY1YS00ZDY2YTEzMzY4YjAiLCJodHRwczovL2lkLmF0bGFzc2lhbi5jb20vYXBwQWNjcmVkaXRlZCI6ZmFsc2V9.pReng9mjTL6tAzy37vSc2tOq6s6mQKnjWaMudv_ur6Q)
3. Screen reader should announce selected option along with its selected state. Proper ARIA attributes (aria-selected/aria-activedescendant) should be implemented ([https://media-cdn.atlassian.com/file/17f6223e-affd-46ea-b4a5-d3587b9298af/artifact/video[…]lZCI6ZmFsc2V9.BYBJ9HfDiLnZw5lJNIw6jVZKGuIRFrLLGdQ5b0f2me4](https://media-cdn.atlassian.com/file/17f6223e-affd-46ea-b4a5-d3587b9298af/artifact/video_1280.mp4/binary/cdn?client=f8316f75-1151-484f-860f-73a63cdf679e&collection=&max-age=2592000&token=eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJmODMxNmY3NS0xMTUxLTQ4NGYtODYwZi03M2E2M2NkZjY3OWUiLCJhY2Nlc3MiOnsidXJuOmZpbGVzdG9yZTpmaWxlOjE3ZjYyMjNlLWFmZmQtNDZlYS1iNGE1LWQzNTg3YjkyOThhZiI6WyJyZWFkIl19LCJleHAiOjE3NzQzNjEwODgsIm5iZiI6MTc3NDM2MDE4OCwiYWFJZCI6IjcxMjAyMDplYWE3Y2UwMy1iYjMxLTQzOTYtYmY1YS00ZDY2YTEzMzY4YjAiLCJodHRwczovL2lkLmF0bGFzc2lhbi5jb20vYXBwQWNjcmVkaXRlZCI6ZmFsc2V9.BYBJ9HfDiLnZw5lJNIw6jVZKGuIRFrLLGdQ5b0f2me4) )

Image

https://cengage.slack.com/archives/C8Y4FR63U/p1774360088347239

**NOTE: Contact the team when the issue is resolved.**

### PR DESCRIPTION
**Pull request by nikitaorliak-cengage**
Closes: #2369

## What I did

Fixed accessibility issues

## Checklist 
- [x] changeset has been added
- [x] Pull request is assigned, labels have been added and ticket is linked
- [x] Pull request description is descriptive and testing steps are listed
- [ ] Corresponding changes to the documentation have been made
- [x] New and existing unit tests pass locally with the proposed changes
- [x] Tests that prove the fix is effective or that the feature works have been added

## How to test

1. Open Storybook/Docs -> Datagrid/Table -> Check new label for the pagination -> Turn on NVDA/VO -> Check that new label is announced correctly 
2. Open Storybook/Docs -> Combobox/Select -> Check that selected items now has `aria-selected="true"` -> Turn on NVDA/VO -> Items should be announced as `Selected`

### CODE REVIEW

File: packages/react-magma-dom/src/components/Table/TablePagination.tsx [hunk 1]
```diff
@@ -285,10 +284,6 @@ export const TablePagination = React.forwardRef<
 
   const previousButton = pageButtons[0];
   const nextButton = pageButtons[pageButtons.length - 1];
-  const currentPageLabel = i18n.table.pagination.currentPageLabel.replace(
```
Comment (olehnoskov-cengage) [inline packages/react-magma-dom/src/components/Table/TablePagination.tsx:288]: Could you delete this `i18n.table.pagination.currentPageLabel` in the `default.ts` file if we no longer use it?

File: packages/react-magma-dom/src/components/Table/TablePagination.tsx [hunk 2]
```diff
@@ -316,11 +311,8 @@ export const TablePagination = React.forwardRef<
         aria-live={AnnouncePoliteness.polite}
         aria-atomic="true"
       >
-        {`${displayPageStart}-${displayPageEnd} ${i18n.table.pagination.ofLabel} ${itemCount} `}
+        {`Page ${page}: ${displayPageStart}-${displayPageEnd} ${i18n.table.pagination.ofLabel} ${itemCount} `}
```
Comment (olehnoskov-cengage) [inline packages/react-magma-dom/src/components/Table/TablePagination.tsx:314]: Do we need to announce, for example, `Page 2: current page`?

Comment (nikitaorliak-cengage) [reply packages/react-magma-dom/src/components/Table/TablePagination.tsx:314]: This block has `aria-atomic="true"` and `aria-live="polite"`, so screenreaders announce it anyway
And yes, we need to announce it for people who use screenreaders

**Review by silvalaura — APPROVED** [review]

**Review by olehnoskov-cengage — APPROVED** [review]
