### PR TITLE
fix(theme): update types for theme in the components

### LINKED ISSUE #901: RM3: Issues with custom themes on some components
**Describe the bug**
The `Heading` and `IconButton` components are not working appropriately with custom themes-- the theme should be generic, like it is for other components such as `Flex`.

**Expected behavior**
All components work as expected with custom themes.

**Screenshots**
Screenshot 2022-08-29 at 20 50 44

**Additional context**
Slack conversation: https://cengage.slack.com/archives/C8Y4FR63U/p1661801266287559

### PR DESCRIPTION
**Pull request by nikitaorliak-cengage**
Closes: #901

## What I did

Update theme types for several components.

## Checklist 
- [x] changeset has been added
- [x] Pull request is assigned, labels have been added and ticket is linked
- [x] Pull request description is descriptive and testing steps are listed
- [ ] Corresponding changes to the documentation have been made
- [x] New and existing unit tests pass locally with the proposed changes
- [ ] Tests that prove the fix is effective or that the feature works have been added

## How to test

Open updated components via IDE -> Check that types for theme now are `theme: ThemeInterface` instead of `theme: any`

### CODE REVIEW

**Review by olehnoskov-cengage — APPROVED** [review]

File: packages/charts/src/components/LineChart/magma-charts.ts [hunk 1]
```diff
@@ -69,7 +71,7 @@ const centeredLabelStyles = { textAnchor: 'middle', ...baseLabelStyles };
 const strokeLinecap = 'round';
 const strokeLinejoin = 'round';
 
-export const magmaTheme: any = {
+export const magmaTheme: ThemeInterface = {
```
Comment (silvalaura) [inline packages/charts/src/components/LineChart/magma-charts.ts:74]: I wonder if this should stay as `any`. This object doesn't match our ThemeInterface (and this line-chart is going to be deprecated soon anyway, so lets skip this one)

**Review by silvalaura — APPROVED** [review]
