### PR TITLE
fix(Combobox): NVDA does not identify the combo-boxes in browse mode

### LINKED ISSUE #1950: [Accessibility] [Global] [Combobox] Basic Usage> NVDA does not identify the combo-boxes in browse mode
[A11Y-517](https://jira.cengage.com/browse/A11Y-517)

**Environment:**
Windows 11/Edge 136/NVDA 2025

**Steps to Reproduce:**
1. Open the URL – https://react-magma.cengage.com/version/4.9.1/api/tooltip/
2. Turn on NVDA and ensure it's running in browse mode.
3. Navigate to the 'Combobox' component page from the left navigation.
4. Under the 'Basic Usage' section, use the down arrow key or the quick navigation key 'C' to navigate through combo-boxes.
5. Observe whether NVDA announces the presence of any combo-boxes.

**Actual Result:**

While navigating in browse mode using arrow keys or quick navigation key ‘C’, NVDA fails to identify any interactive combo-box components on the page. Only the associated labels such as “Combobox”, “Initial selected by item”, and “Initial highlighted index” are announced, but the actual combo-box inputs are completely skipped during arrow key navigation.

Refer to screencast:
https://app.screencast.com/NIeKZZlovJwWS

Note: This issue is reproducible for all of the comboboxes present on the page.

**Expected Result:**
https://app.screencast.com/6k7IRgqtSBvjq

NVDA should correctly detect and announce the presence of combo-box components in browse mode when using navigation keys like arrow keys or quick key 'C'. This allows screen reader users to locate and interact with form elements efficiently.

**User Impact:**
Screen reader users relying on browse mode navigation may not be aware of the presence of combo-boxes on the page, causing them to miss form fields entirely or incorrectly assume the page lacks interactivity.

WCAG Guideline: 4.1.2 Name, Role, Value (A)

**Bug Fix Recommendation:**
a) Ensure each combo-box component is implemented using semantic markup or appropriate ARIA roles such as role="combobox", aria-expanded, aria-controls, aria-activedescendant, and aria-labelledby/aria-label.
b) Verify that the combo-boxes are properly exposed to the accessibility tree and recognized in virtual/browse mode in NVDA.

### PR DESCRIPTION
**Pull request by olehnoskov-cengage**
Closes: #1950

## What I did
- Improved NVDA Browse Mode navigation across the page for Combobox and MultiCombobox.

## Checklist 
- [x] changeset has been added
- [x] Pull request is assigned, labels have been added and ticket is linked
- [x] Pull request description is descriptive and testing steps are listed
- [ ] Corresponding changes to the documentation have been made
- [ ] New and existing unit tests pass locally with the proposed changes
- [ ] Tests that prove the fix is effective or that the feature works have been added

## How to test
Go to **Storybook** -> Combobox -> Full Page example -> Turn on NVDA -> navigate across comboboxes via pressing `C` in browse mode.

Go to **Docs** -> Components ->  Combobox ->Navigate across all examples via pressing `C` in browse mode.

### CODE REVIEW

File: packages/react-magma-dom/src/components/Combobox/ComboboxInput.tsx [hunk 1]
```diff
@@ -199,9 +198,10 @@ export function ComboboxInput<T>(props: ComboboxInputProps<T>) {
   return (
     <div ref={setReference}>
       <ComboBoxContainer
-        {...getComboboxProps()}
+        {...(getComboboxProps && getComboboxProps().ref
+          ? { ref: getComboboxProps().ref }
+          : {})}
         hasError={hasError}
-        disabled={disabled}
```
Comment (silvalaura) [inline packages/react-magma-dom/src/components/Combobox/ComboboxInput.tsx:204]: Why are we removing the disabled functionality?

File: .changeset/fix-Combobox-accessibility.md [hunk 2]
```diff
@@ -0,0 +1,6 @@
+---
+
```
Comment (silvalaura) [inline .changeset/fix-Combobox-accessibility.md]: We may want to remove this space just in case? Not sure if it'll affect our automation

**Review by silvalaura — COMMENTED** [review]
This one is hard to test, but I think this is right 👍

File: packages/react-magma-dom/src/components/Combobox/ComboboxInput.tsx (hunk 1 above)
Comment (olehnoskov-cengage) [reply packages/react-magma-dom/src/components/Combobox/ComboboxInput.tsx:204]: 1. `ComboBoxContainer` doesn't have this prop.
2. `getComboboxProps()` didn't have the `disabled` attribute before, and it did nothing. Now, I need only the `ref` value for `ComboBoxContainer` to fix the current issue and not break the downshift functionality.
3. Combobox works in the same way as before.

Image

**Comment by olehnoskov-cengage** [comment]
> This one is hard to test, but I think this is right 👍

Actually, it's easy to test.
We need to turn on NVDA (Windows) and press `C` to navigate across all combobox examples.
[Screencast from 11.11.25 11:31:13.webm](https://github.com/user-attachments/assets/dbb7dd0a-4741-4c87-8bcb-1a1a580e3da4)

**Review by silvalaura — APPROVED** [review]

**Review by nikitaorliak-cengage — APPROVED** [review]
