### PR TITLE
fix(Table/Datagrid): Improve screen reader announcements for table navigation and pagination

### LINKED ISSUE #1797: Table: NVDA reads whole table data at once upon navigating to it via Tab key
**Describe the bug**
NVDA screen reader reads hole table data (column headers, rows and cells values) at once upon navigating to it via Tab key

**To Reproduce**
1. Go to React Magma Docs
2. Open Table -> Basic Usage
3. Turn on NVDA screen reader
4. Move to table example via Tab key
5. Verify NVDA screen reader reads hole table data (column headers, rows and cells values) at once

**Expected behavior**
Screen reader should read only the table name. Headers/cells should be read when user navigates to them

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser:  Chrome, v. 137, Firefox 139
 - Screen reader: NVDA

**Additional context**
May be connected to https://github.com/cengage/react-magma/issues/1769

### LINKED ISSUE #1947: [Accessibility] [Global] [Datagrid] Basic Usage> Screen reader automatically starts reading updated table content upon changing the value of 'Rows per page' combo-box
[A11Y-528](https://jira.cengage.com/browse/A11Y-528)

**Environment:**
Windows 11/Chrome 137/JAWS 2025
Windows 11/Edge 136/NVDA 2025
Mac 15/Safari/VoiceOver

**Steps to Reproduce:**
1. Open the URL – https://react-magma.cengage.com/version/4.9.1/api/tooltip/
2. Turn on the screen reader (JAWS/NVDA/VoiceOver).
3. Navigate to the Datagrid component page from the left navigation.
4. Navigate to the Basic Usage section.
5. Use TAB to move to the Rows per page combo-box and change its value (e.g., from 10 to 20).
6. Observe the screen reader behavior after the update.

**Actual Result:**
Upon changing the value of the Rows per page combo-box, the screen reader automatically begins reading the entire updated table content without any user-initiated navigation. This unexpected and verbose behavior occurs immediately after the value is changed, even though focus remains on the combo-box. The screen reader starts reading row-by-row, often mid-sentence, disrupting the user’s flow and causing cognitive overload. This behavior is especially problematic when the table contains a large number of rows, making it difficult for screen reader users to understand the structure or regain control of navigation.

Refer to screencast:
https://app.screencast.com/95HSUzEslgK8H

Note: This issue is reproducible for all Datagrid variants that use the Rows per page combo-box.

**Expected Result:**
Screen readers should not automatically read the updated table content. Instead, the updated pagination status such as "Showing 1 - 20 of 25" should be automatically announced, allowing users to manually explore the table as needed.

**User Impact:**
Uncontrolled verbosity can disorient screen reader users and disrupt their navigation flow. Users may miss important structural context or find it difficult to regain their place in the page.

WCAG Guideline: 3.2.2 On Input (A)

Bug Fix Recommendation:

a) Prevent automatic reading of the entire table by avoiding programmatic DOM focus shifts or use of live regions that contain the full table content.
b) Use an aria-live="polite" region to automatically announce the updated pagination status i.e. "Showing 1 - 20 of 25" after the change.
c) Allow users to explore the updated content at their own pace.

### PR DESCRIPTION
**Pull request by moathabuhamad-cengage**
fix(Table/Datagrid): Improve screen reader announcements for table navigation and pagination

Closes: #1797, #1947

## What I did
**Bug fix** - Fixed accessibility issues with screen reader announcements for Table and Datagrid components

- Removed `aria-live="polite"` from Datagrid table to prevent automatic reading of entire table content when rows per page changes (fixes #1947)
- Added `aria-live="polite"` to TablePagination page count to announce pagination status updates appropriately 
- Added proper ARIA attributes (`role="region"`, `aria-label`/`aria-labelledby`) to scrollable table wrapper to prevent verbose screen reader announcements when tabbing to tables (fixes #1797)

These changes ensure compliance with WCAG 3.2.2 On Input (Level A) and improve the user experience for screen reader users by preventing disruptive, verbose announcements.

## Screenshots
N/A - Accessibility fix that affects screen reader behavior only

## Checklist 
- [x] changeset has been added
- [ ] Pull request is assigned, labels have been added and ticket is linked
- [x] Pull request description is descriptive and testing steps are listed
- [ ] Corresponding changes to the documentation have been made
- [x] New and existing unit tests pass locally with the proposed changes
- [x] Tests that prove the fix is effective or that the feature works have been added

### Testing Issue #1947 (Datagrid pagination)
1. Open the Datagrid Basic Usage example in Storybook
2. Enable a screen reader (NVDA, JAWS, or VoiceOver)
3. Navigate to the "Rows per page" combo-box
4. Change the value (e.g., from 10 to 20)
5. **Expected:** Screen reader announces only the updated pagination status (e.g., "1-20 of 25")
6. **Expected:** Screen reader does NOT automatically read the entire table content

### Testing Issue #1797 (Table focus)
1. Open the Table Basic Usage example in Storybook
2. Enable a screen reader (NVDA on Windows)
3. Use Tab key to navigate to the table
4. **Expected:** Screen reader announces only the table title/caption
5. **Expected:** Screen reader does NOT read all table headers, rows, and cells at once

### Edge cases to verify:
- Non-scrollable tables should not receive focus when tabbing
- Scrollable tables with interactive elements (buttons, inputs) should not receive tabIndex
- Scrollable tables without interactive elements should be focusable and announce their accessible name
- All existing table and datagrid functionality remains intact

### CODE REVIEW

File: packages/react-magma-dom/src/components/Table/Table.tsx [hunk 1]
```diff
@@ -309,6 +309,17 @@ export const Table = React.forwardRef<HTMLTableElement, TableProps>(
             minWidth={minWidth}
             tabIndex={shouldHaveTabIndex ? 0 : null}
             ref={tableWrapperRef}
+            role={shouldHaveTabIndex ? 'region' : null}
+            aria-label={
```
Comment (olehnoskov-cengage) [inline packages/react-magma-dom/src/components/Table/Table.tsx]: Could you extract this value `shouldHaveTabIndex && typeof tableTitle === 'string' ? tableTitle` and the value on the `319 line`?

**Review by nikitaorliak-cengage — CHANGES_REQUESTED** [review]
**Bug 1:**
1. Open Storybook > Datagrid -> Default
2. Click on the `Next` button (now we can see 11-20 of 25)
3. Move focus back to `Rows per page` and select 50/100
4. Check the label, now it shows 51-25 of 25 

[Screencast from 01-21-2026 02:41:50 PM.webm](https://github.com/user-attachments/assets/320db2f8-db82-4472-8fa7-ca6194109806)

**Bug 2:**
1. Open Storybook > Datagrid -> Default
2. Widnwos + Firefox + NVDA, MacOS + Chrome/Firefox + VO
3. Change `Rows per page` value
4. Screenreader announces it twice (MacOS + Safari + VO announces it 4 times)
image
image

**Bug 3:**
1. Open Storybook -> Table -> Default
2. Windows + Chrome + NVDA (Works as expected for Firefox)
3. Using the tab, go to the table
4. Screenreader announces the whole table (Same for scrollable)
image

**Bug 4:** (Not sure)
1. Open Storybook -> Table -> Default
2. MacOS + Chrome + VO
3. Using the tab, go to the table
4. Screenreader doesn't announce the table at all (Works fine with scrollable, check screen 2)
image
image

**Bug 5:**
1. Open Storybook -> Table -> Default
2. Windows + Chrome + NVDA (Works as expected for Firefox)
3. Using the tab, go to the `Next` or `Previous` button
4. Click on it
5. Screenreader doesn't announce updated rows (11-20 of 23) 
image

**Comment by olehnoskov-cengage** [comment]
Screenshot from 2026-01-21 12-08-14

Screen reader announces only the table title/caption -> **NVDA announces the whole table** when the user navigates to the table.

**Review by silvalaura — APPROVED** [review]
