### PR TITLE
fix(Dropdown): Add aria controls for dropdown trigger button.

### LINKED ISSUE #2024: [Accessibility] [Global] [Dropdown] [Basic Usage]> Dropdown button should include aria-controls to reference the associated menu
[A11Y-604](https://jira.cengage.com/browse/A11Y-604)

**Environment:**
Windows 11 / Chrome 137 / JAWS 2025
Windows 11 / Edge 136 / NVDA 2025
MacOS 15 / Safari / VoiceOver

**Steps to Reproduce:**
1. Open the URL - https://react-magma.cengage.com/version/4.9.1/api/dropdown/
2. Launch 'Loading Indicator'' component page from left navigation.
3. Navigate to the dropdown button under 'Basic Usage' and observe the accessibility attributes.

**Actual Result:**
The dropdown menu button does not include the aria-controls attribute. As a result, screen readers are not informed about the relationship between the button and the menu it controls.

Refer to Screencast: https://app.screencast.com/0skDXCP8oKAPw

Instance: This applies to all the sub components.

**Expected Result:**
The dropdown menu button should include the aria-controls attribute with a value matching the id of the associated menu element. This helps assistive technologies understand the control relationship between the button and the dropdown content.

**User Impact:**
Screen reader users may not understand that the button controls a specific menu, leading to confusion or difficulty in navigating the interface.

WCAG Guidelines:
4.1.2 Name, Role, Value (Level A)

**Bug Fix Recommendation:**

Add aria-controls="dropdownMenuId" to the dropdown button, where dropdownMenuId is the id of the corresponding menu element.
Ensure the menu element has a matching id and is properly associated with the button.

### PR DESCRIPTION
**Pull request by olehnoskov-cengage**
Closes: #2024

## What I did
- Added `aria-controls` attribute for DropdownButton.

## Checklist 
- [x] changeset has been added
- [x] Pull request is assigned, labels have been added and ticket is linked
- [x] Pull request description is descriptive and testing steps are listed
- [ ] Corresponding changes to the documentation have been made
- [x] New and existing unit tests pass locally with the proposed changes
- [ ] Tests that prove the fix is effective or that the feature works have been added

## How to test
Go to Storybook -> Dropdown -> Default -> `aria-controls` for the trigger button, and the `id` for the dropdown content must be the same.
Go to Storybook -> Dropdown -> Split Button -> `aria-controls` for the trigger button, and the `id` for the dropdown content must be the same.
Go to Storybook -> Dropdown -> Alignment Button -> `aria-controls` for the trigger button, and the `id` for the dropdown content must be the same.

### CODE REVIEW

File: packages/react-magma-dom/src/components/Dropdown/DropdownContent.tsx [hunk 1]
```diff
@@ -94,6 +94,7 @@ export const DropdownContent = React.forwardRef<
   return (
     <div
       data-testid={'dropdownContentWrapper'}
+      id={'dropdownMenuId'}
```
Comment (silvalaura) [inline packages/react-magma-dom/src/components/Dropdown/DropdownContent.tsx]: should this id be unique, for the cases of multiple dropdown menus on the same page?

Comment (olehnoskov-cengage) [reply packages/react-magma-dom/src/components/Dropdown/DropdownContent.tsx]: Yes, you are right. Add some unique data for this ID.

**Review by nikitaorliak-cengage — APPROVED** [review]

**Review by silvalaura — APPROVED** [review]
