### PR TITLE
fix(Tabs & NavTabs): Update focus behavior and aria-labels.

### LINKED ISSUE #2072: [Accessibility] [Global] [Combobox] Clearable issues with screenreader
[A11Y-518](https://jira.cengage.com/browse/A11Y-518)
[A11Y-519](https://jira.cengage.com/browse/A11Y-519)

**Issue 1:** 
**[Accessibility] [Global] [Combobox] Clearable> JAWS user is unable to find and access x' (Reset) button when virtual cursor is ON.**

Environment:
Windows 11/Chrome 137/JAWS 2025

Steps to Reproduce:

1. Open the URL – https://react-magma.cengage.com/version/4.9.1/api/tooltip/
2. Turn on the JAWS screen reader.
3. Navigate to the 'Combobox' component page from the left navigation.
4. Under the 'Clearable' section, select a value such as “Green” from the combobox.
5. Press the TAB key to navigate to the 'x' (Reset) button that appears next to the Clearable combobox.
6. Observe how JAWS announces the control.

Actual Result:
After making any selection from the Clearable combobox, when user presses TAB key, JAWS again identifies the combobox reading it as "Clearable edit combo collapsed Green", it does not identify the 'x' (Reset) button and thus JAWS users are unable to execute the Reset action. To find and access 'x' (Reset) button, JAWS users need to firstly turn off the virtual cursor using Insert + Z command, which is not the ideal behavior, and users won't expect this at all.

Refer to screencast:
https://app.screencast.com/OISNXrc0YMymb

Instances:

This issue is reproducible for all similar reset ('x') buttons, including in the following combo-boxes:

a) Clearable with Defaults combobox
Screencast: https://app.screencast.com/xK8iwRS1yJ3lm
b) Internationalization combobox
Screencast: https://app.screencast.com/LaDFd9gV2TmR0

Expected Result:
JAWS users should be able to find and access the 'x' (Reset) button without turning OFF the virtual cursor, otherwise a hidden instruction should be associated with the component informing users about this behavior.

User Impact:
If the control’s accessible name and role is not announced in normal virtual cursor, screen reader users may not recognize this element at all, and may not know they can activate it to reset their selection.

WCAG Guideline: 4.1.2 Name, Role, Value (A)

Bug Fix Recommendation:
a) Ensure the reset icon is implemented as a native <button> element or includes role="button" with correct aria-label.
b) Avoid using div or span without explicit role and interactivity definitions.

**Issue 2:**
**[Accessibility] [Global] [Combobox] Clearable> Screen reader does not announce any confirmation message upon activating 'Reset' (x) button**

Environment:
Windows 11/Chrome 137/JAWS 2025
Windows 11/Edge 136/NVDA 2025
Mac 15/Safari/VoiceOver

Steps to Reproduce:

1. Open the URL – https://react-magma.cengage.com/version/4.9.1/api/tooltip/
2. Turn on the screen reader (JAWS/NVDA/VoiceOver).
3. Navigate to the 'Combobox' component page from the left navigation.
4. Under the 'Clearable' section, select a value such as “Green” from the combobox.
5. Press TAB to move focus to the 'x' (Reset) button and activate it using SPACE or ENTER.
6. Observe whether any confirmation message is announced by the screen reader.

Actual Result:

Upon activating the 'x' (Reset) button, the selected value is cleared visually. However, no confirmation message (e.g., "Green has been removed") is announced by the screen reader.

Refer to screencast:
https://app.screencast.com/MhAsMCwgKJWda

Instances:

This issue is reproducible across all similar combo-box reset buttons, including:

a) Clearable with Defaults combobox
Screencast: https://app.screencast.com/YYqunkoG3dMyN
b) Internationalization combobox
Screencast: https://app.screencast.com/DgrHDz1ow0OvN

Expected Result:

Upon resetting the combobox selection, a confirmation message should be programmatically announced to screen reader users, indicating that the selected value has been removed.

User Impact:
Without audible feedback, screen reader users may not realize that the selection has been cleared, leading to confusion or repeated interaction attempts.

WCAG Guideline: 4.1.3 Status Messages (AA)

Bug Fix Recommendation:

a) Use an ARIA live region (e.g., aria-live="polite") to announce a confirmation message such as "Green has been removed" when the reset action is performed.
b) Make sure the live region is properly updated in the DOM for the screen reader to detect the change.

### LINKED ISSUE #2094: Accessibility] [Tab]  The selected tab content is not read by screen reader
[A11Y-623](https://jira.cengage.com/browse/A11Y-623)
[A11Y-624](https://jira.cengage.com/browse/A11Y-624)
[A11Y-625](https://jira.cengage.com/browse/A11Y-625)

**Issue 1:**
**Accessibility] [Tab] Border position > The selected tab content is not read by screen reader**

Environment:
Windows 11/Chrome 137/JAWS 2025
Windows 11/Edge 136/NVDA 2025

Steps to Reproduce:

1. Open the URL – https://react-magma.cengage.com/version/4.9.1/api/tabs/
2. Turn on the screen reader (JAWS/NVDA).
3. Navigate to the 'Tab' component page from the left navigation.
4. Navigate to "Border position" element and select different tab.
5. Verify that the selected tab content is not read.

Actual Result:

The selected tab content is not read by screen reader

Refer to screencast:
https://app.screencast.com/WVHYunyx3Q8xg

Instance:
The same issue is present for tab grouping present on the right side.
Screencast: https://app.screencast.com/wMwtsRDNDBnp0

Expected Result:

As the tab grouping is at the bottom and the content is above the tab grouping the changed content should be read by screen reader.

User Impact:
Without audible feedback, screen reader users may not realize that the tab content is displayed.

WCAG Guideline: 4.1.3 Status Messages (AA)

Bug Fix Recommendation:

a) Use an ARIA live region (e.g., aria-live="polite") to announce a confirmation message such as tab content or tab content heading
b) Make sure the live region is properly updated in the DOM for the screen reader to detect the change."

**Issue 2:**
**[Accessibility] [Tab] Border position > After selecting next and previous buttons there is no update read by screen reader.**

Environment:
Windows 11/Chrome 137/JAWS 2025
Windows 11/Edge 136/NVDA 2025

Steps to Reproduce:

1. Open the URL – https://react-magma.cengage.com/version/4.9.1/api/tabs/
2. Turn on the screen reader (JAWS/NVDA).
3. Navigate to the 'Tab' component page from the left navigation.
4. Navigate to "Scrollable " element and click forward button
5. Verify that there is no update provided to screen reader users

Actual Result:

There is no info or update message read by screen reader after user clicks forward button.

Refer to screencast:
Scrollable

Note:
This issue is also present when user clicks previous button as well.

Expected Result:

As new tabs are displayed after pressing forward button there should be update or info given to screen reader users.

User Impact:
Without audible feedback, screen reader users may not realize that there has been a change on the page.

WCAG Guideline: 4.1.3 Status Messages (AA)

Bug Fix Recommendation:

a) Use an ARIA live region (e.g., aria-live="polite") to announce a confirmation message such as "moved forward" when the reset action is performed.
b) Make sure the live region is properly updated in the DOM for the screen reader to detect the change."

**Issue 2:**
**[Accessibility] [Tab] Scrollable > After selecting next and previous buttons the focus is moving out of tab grouping**

Environment:
Windows 11/Chrome 137/JAWS 2025
Windows 11/Edge 136/NVDA 2025

Steps to Reproduce:

1. Open the URL – https://react-magma.cengage.com/version/4.9.1/api/tabs/
2. Turn on the screen reader (JAWS/NVDA).
3. Navigate to the 'Tab' component page from the left navigation.
4. Navigate to "Scrollable" element and click forward button
5. press TAB key and verify that the focus is moving out of tab grouping

Actual Result:

The TAB focus is moving out of tab grouping after pressing forward button

Refer to screencast:
https://app.screencast.com/qQBo7AxoBzKPm

Note: This issue is present for previous button as well

Expected Result:

User after clicking forward button the first tab of newly displayed tab should be focused

User Impact:
As the focus is moving out of the tab grouping after pressing forward button screen reader users will be disoriented

WCAG Guideline: 2.4.3 Focus Order (A)

Bug Fix recommendation:
Use JS function onFocus() to explicitly put focus on the first tab of newly displayed tabs.

**Extra task:**
Hey team. I'm experiencing a kind of weird bug on the [Tabs page](https://react-magma.cengage.com/version/4.12.1/api/tabs/). When it loads, it takes me halfway down the page to "Scrollable Vertical Tabs" section. Anyone else getting this same behavior?

### PR DESCRIPTION
**Pull request by olehnoskov-cengage**
Closes: #2072
Closes: #2094

- Updated focus behavior during scrolling tabs
- Updated aria-labels for `Tabs` and `Nav tabs`
- Fixed broken Combobox example
- Fixed broken Button example

## Checklist 
- [x] changeset has been added
- [x] Pull request is assigned, labels have been added and ticket is linked
- [x] Pull request description is descriptive and testing steps are listed
- [x] Corresponding changes to the documentation have been made
- [x] New and existing unit tests pass locally with the proposed changes
- [x] Tests that prove the fix is effective or that the feature works have been added

## How to test
Go to Storybook -> Tabs -> Scrolling -> press twice on the `Next` button -> NVDA/VO should announce `Scrolled tabs forward` -> focus should be moved to `Previous` button -> Press on the `Previous` button -> NVDA/VO should announce `Scrolled tabs back.` 

Go to Storybook -> Nav Tabs -> Scrolling -> press on the `Next` button ->  NVDA/VO should announce `Scrolled tabs forward` -> focus should be moved to `Previous` button -> NVDA/VO should announce `Scrolled tabs back.` 

Go to Storybook -> Tabs -> Icon -> Focus on First item-> NVDA/VO should announce `First item + Email ` -> Focus on Second item->  NVDA/VO should announce `First item + Android ` 

Go to Docs -> Components -> Combobox -> Internationalization -> example should be fixed
Go to Docs -> Components -> Button -> Types -> type text -> press on Reset button -> input field should be cleared

### CODE REVIEW

**Review by nikitaorliak-cengage — APPROVED** [review]

**Comment by silvalaura** [comment]
image
Seeing this error when adding a second item in the multi i18n example

File: packages/react-magma-dom/src/components/NavTabs/NavTabs.tsx [hunk 1]
```diff
@@ -225,11 +250,14 @@ export const NavTabs = React.forwardRef<
...
-        onClick={handleEndScrollClick}
+        onClick={handleNextScrollWithAnnouncement}
         orientation={orientation || TabsOrientation.horizontal}
         ref={nextButtonRef}
         theme={theme}
       />
+      <VisuallyHidden>
+        <Announce>{scrollAnnouncement}</Announce>
+      </VisuallyHidden>
     </StyledContainer>
```
Comment (silvalaura) [inline packages/react-magma-dom/src/components/NavTabs/NavTabs.tsx:261]: Do we need to announce the content too?

Comment (olehnoskov-cengage) [reply packages/react-magma-dom/src/components/NavTabs/NavTabs.tsx:261]: Related to this comment -https://github.com/cengage/react-magma/issues/2094#:~:text=grouping%20the%20changed-,content,-should%20be%20read

Yes, we should.

**Review by moathabuhamad-cengage — APPROVED** [review]
