### PR TITLE
fix(ToggleButton): transform issue

### LINKED ISSUE #2005: ToggleButton: support text transform
**Describe the bug**
The ToggleButton component should support the textTransform prop, but it is not passed down to the component. We should make sure to pass `{...others}` down to it.

**Expected behavior**
ToggleButton component supports `textTransform={ButtonTextTransform.none}`

**Screenshots**
Image

### PR DESCRIPTION
**Pull request by nikitaorliak-cengage**
Closes: #2005 

## What I did

Added {...other} to ToggleButton, now it supports `textTransform` prop correctly.
Added tests for this fix.

## Checklist 
- [x] changeset has been added
- [x] Pull request is assigned, labels have been added and ticket is linked
- [x] Pull request description is descriptive and testing steps are listed
- [ ] Corresponding changes to the documentation have been made
- [x] New and existing unit tests pass locally with the proposed changes
- [x] Tests that prove the fix is effective or that the feature works have been added

## How to test

Open Storybook -> ToggleButton -> Text -> Controls -> Check behavior

### CODE REVIEW

**Review by silvalaura — APPROVED** [review]

**Review by olehnoskov-cengage — APPROVED** [review]

File: packages/react-magma-dom/src/components/ToggleButton/ToggleButton.tsx [hunk 1]
```diff
@@ -189,6 +190,7 @@ export const ToggleButton = React.forwardRef<
     <>
       {icon ? (
         <StyledToggleButtonIcon
+          {...other}
```
Comment (olehnoskov-cengage) [inline packages/react-magma-dom/src/components/ToggleButton/ToggleButton.tsx]: Maybe we can create a variable to collect the same attributes for `StyledToggleButtonIcon` and `StyledToggleButtonText`?

**Review by olehnoskov-cengage — APPROVED** [review]
