### PR TITLE
fix(Textarea): Fix aria describedby to announce the helper text.

### LINKED ISSUE #2112: TextArea: Screen reader doesn't announce helper message change
**Describe the bug**
Screen reader doesn't announce helper message change for max length (# characters left) like it does for input element. The reason is because we doesn't add aria-describedby attribute when we have only maxCount props for textarea.

**To Reproduce**
1. Go to 'https://react-magma.cengage.com/version/4.10.1/api/textarea/#character_counter'
2. Turn on NVDA or VO.
3. Type text in the text area
4. NVDA and VO announce only the typed text, not the helper message.

**Expected behavior**
 NVDA and VO should announce the helper message when the user changes the text area value.

**Screenshots**

Image

**Additional context**
[Slack request](https://cengage.slack.com/archives/C8Y4FR63U/p1764935929079959)

### PR DESCRIPTION
**Pull request by olehnoskov-cengage**
Closes: #2112

## What I did
- Added announcement helper message for `Textarea`.
- Add an optional `aria-label` prop for **NavTabs**

## Screenshots
Screenshot from 2025-12-08 12-23-48

## Checklist 
- [x] changeset has been added
- [x] Pull request is assigned, labels have been added and ticket is linked
- [x] Pull request description is descriptive and testing steps are listed
- [ ] Corresponding changes to the documentation have been made
- [ ] New and existing unit tests pass locally with the proposed changes
- [ ] Tests that prove the fix is effective or that the feature works have been added

## How to test
Go to Storybook -> `Textarea` -> `On Clear` -> Turn on NVDA/VO -> Type text -> NVDA/VO should announce helper text

### CODE REVIEW

**Review by moathabuhamad-cengage — APPROVED** [review]
works on JAWS as well

**Comment by nikitaorliak-cengage** [comment]
Doesn't work on Windows 10 + Firefox
image

Everything else works as expected 

P.S. Windows + Firefox works as expected with `aria-labelledby` instead of `aria-describedby`.

File: packages/react-magma-dom/src/components/NavTabs/NavTabs.tsx [hunk 1]
```diff
@@ -20,7 +20,7 @@ import { ButtonNext, ButtonPrev } from '../Tabs/TabsScrollButtons';
 import { useTabsMeta } from '../Tabs/utils';
 
 export interface NavTabsProps extends Omit<TabsProps, 'onChange'> {
-  'aria-label': string;
+  'aria-label'?: string;
```
Comment (silvalaura) [inline packages/react-magma-dom/src/components/NavTabs/NavTabs.tsx:23]: 🙏

**Review by silvalaura — APPROVED** [review]
