### PR TITLE
fix(Pagination): Add announcement  when selected page updates.

### LINKED ISSUE #2025: [Accessibility] [Pagination] Basic Pagination > Page change status not announced by screen reader when using Previous/Next buttons.
[A11Y-585](https://jira.cengage.com/browse/A11Y-585)

**Environment:**
Windows 11 / Chrome 137 / JAWS 2025
Windows 11 / Edge 136 / NVDA 2025
Mac 15 / Safari / VoiceOver

**Steps to Reproduce:**
1. Open the URL – https://react-magma.cengage.com/version/4.9.1/api/pagination/
2. Turn on a screen reader (JAWS/NVDA/VoiceOver).
3. Launch 'Pagination' component page from left navigation.
4. On the 'Pagination' page, under 'Basic Pagination'.
5. Use the Previous or Next button to change pages.
6. Observe whether any status message is announced by the screen reader.

**Actual Result:**
When the user changes the page using the Previous or Next button, no status message is announced by the screen reader. There is no indication of the current page or total number of pages.

Refer to Screencast: https://app.screencast.com/vHpBZWr6GZNF9

**Expected Result:**
When the user changes the page using the Previous or Next button, a status message should be announced, such as:
"[Title of the page] page `<n>` of `<m>` " (for example:- search results page 1 of 10.
where:
n = current page number
m = total number of pages

**User Impact:**
Screen reader users are left unaware of which page they are on after navigating, which can lead to confusion and difficulty in understanding the context of the content being viewed.

WCAG Guidelines:
4.1.3 Status Messages (Level AA)

**Bug Fix Recommendation:**
Use an ARIA live region (e.g., aria-live="polite") to announce the current page status dynamically when the page changes.

### PR DESCRIPTION
**Pull request by olehnoskov-cengage**
Closes: #2025 

## What I did
- Added announcement for `Pagination` when the selected page changes.

## Checklist 
- [x] changeset has been added
- [x] Pull request is assigned, labels have been added and ticket is linked
- [x] Pull request description is descriptive and testing steps are listed
- [ ] Corresponding changes to the documentation have been made
- [ ] New and existing unit tests pass locally with the proposed changes
- [ ] Tests that prove the fix is effective or that the feature works have been added

## How to test
Go to Storybook -> Pagination -> Default -> Turn on VO/NVDA -> when the selected page changes -> screen reader announces the selected page number.

Go to Storybook -> Pagination -> Simple Pagination -> behaviour should work as before.

### CODE REVIEW

File: packages/react-magma-dom/src/components/Pagination/Pagination.tsx [hunk 1]
```diff
@@ -247,6 +250,9 @@ export const Pagination = React.forwardRef<HTMLDivElement, PaginationProps>(
                         >
                           {page}
                         </PageButton>
+                        <VisuallyHidden>
+                          <Announce>{`${other.isSelected ? pageAriaLabel(page, count, i18n.simplePagination) : ''}`}</Announce>
```
Comment (silvalaura) [inline packages/react-magma-dom/src/components/Pagination/Pagination.tsx]: Instead of `other.isSelected`, can we destructure isSelected?

**Review by silvalaura — COMMENTED** [review]
I am getting undefined on the SimplePagination storybook example when I don't select a page by default or change anything in the component:

Image

**Review by moathabuhamad-cengage — COMMENTED** [review]
it announcing the change twice with JAWS 🤔

**Comment by nikitaorliak-cengage** [comment]
MacOS announces it twice on a simple and classic Paginations, and in addition, after selecting a new page before the `...`, the focus moves to the next one, but the screen reader doesn't announce it.

image

File: packages/react-magma-dom/src/components/Pagination/utils.ts [hunk 2]
```diff
@@ -0,0 +1,24 @@
...
+        ${count}
+        ${count <= 1 ? pagination.pageLabel : pagination.pagesLabel}`;
+};
+
+export const pageAriaLabel = (
+  selectedPage: number,
+  count: number,
+  pagination: PaginationI18n
+) => {
+  return `${pagination.pageNumberLabel}
```
Comment (silvalaura) [inline packages/react-magma-dom/src/components/Pagination/utils.ts]: Can this all be in one line?
Image

**Review by silvalaura — APPROVED** [review]

**Review by nikitaorliak-cengage — APPROVED** [review]
